#!/usr/bin/env bash
# 
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script with sudo."
  exit 1
fi

apt update -y

apt install nginx -y

cd /var/www/html || exit

rm -rf ./*

echo "Hello World!" >> index.html
echo "Ceci n'est pas une page" >> 404.html

CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name malloc.tech www.malloc.tech;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=xvFZjo5PgG0 permanent;
	}
    error_page 404 /404.html;

    location = /404.html {
        root /var/www/html;
        internal;
    }
}"

bash -c "echo -e '$CONFIG' > /etc/nginx/sites-enabled/default"

service nginx restart
