#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd,
# in this format {Username}:{User ID}:{Home directory}
while IFS=: read -r username _ uid _ _ home _; do
    echo "$username:$uid:$home"
done < "/etc/passwd"
