#!/bin/usr/env bash
sudo apt install -y ufw
sudo ufw disable
echo y | sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
echo y | sudo ufw enable
sudo ufw status
