#!/usr/bin/env bash
# This script is used to configure the Nginx user for the container.
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
systemctl stop apache2
systemctl start nginx
