#!/usr/bin/env bash
# This script is used to demonstrate how to use a private key for SSH authentication.
# It assumes that the private key file is located in the user's home directory and is named "id_rsa".
# The script sets the appropriate permissions for the private key file, and then uses the SSH command
# to connect to a remote server using the private key for authentication.
# Replace "user" and "server" with the actual username and server address respectively.
# Usage: ./0-use_a_private_key
# 
ssh -i ~/.ssh/school ubuntu@8.8.8.8 
